---

- name: Prepare webservers
  hosts: all
  become: true

  roles:
    - { role: geerlingguy.pip }
    - { role: datadog.datadog }

- name: Deploy application
  hosts: all
  remote_user: ubuntu
  become: true

  tasks:
    - name: Log into DockerHub
      community.docker.docker_login:
        username: 1g0rbm
        password: "{{ docker_password }}"

    - name: Run container
      community.docker.docker_container:
        name: Application
        image: 1g0rbm/devops-example-app
        published_ports:
          - 3000:3000
        restart_policy: always
        restart: true
        container_default_behavior: no_defaults
        pull: true
        env:
          SERVER_MESSAGE: '{{ ansible_default_ipv4.address }}'
