---

- name: Prepare webservers
  hosts: all
  become: true

  tasks:
    - name: Install packages
      ansible.builtin.apt:
        name: python3-pip
        update_cache: true
      become: true

    - name: Install Docker Module for Python
      ansible.builtin.pip:
        name: docker

- name: Deploy application
  hosts: all
  remote_user: ubuntu
  become: true

  tasks:
    - name: Log into DockerHub
      community.docker.docker_login:
        username: 1g0rbm
        password: "{{ docker_password }}"

    - name: Run container
      community.docker.docker_container:
        name: Application
        image: 1g0rbm/devops-example-app
        published_ports:
          - 3000:3000
        restart_policy: always
        restart: true
        container_default_behavior: no_defaults
        pull: true
        env:
          SERVER_MESSAGE: '{{ ansible_default_ipv4.address }}'

- name: Setting up monitoring
  hosts: all
  become: true
  roles:
    - role: datadog.datadog